cmd_drivers/net/wireless/realtek/rtl8188EUS/platform/platform_ops.o := /usr/local/arm/gcc-linaro-4.9.4-2017.01-x86_64_arm-linux-gnueabihf/bin/arm-linux-gnueabihf-gcc -Wp,-MD,drivers/net/wireless/realtek/rtl8188EUS/platform/.platform_ops.o.d  -nostdinc -isystem /usr/local/arm/gcc-linaro-4.9.4-2017.01-x86_64_arm-linux-gnueabihf/bin/../lib/gcc/arm-linux-gnueabihf/4.9.4/include -I./arch/arm/include -Iarch/arm/include/generated/uapi -Iarch/arm/include/generated  -Iinclude -I./arch/arm/include/uapi -Iarch/arm/include/generated/uapi -I./include/uapi -Iinclude/generated/uapi -include ./include/linux/kconfig.h -D__KERNEL__ -mlittle-endian -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -Werror-implicit-function-declaration -Wno-format-security -std=gnu89 -fno-dwarf2-cfi-asm -fno-ipa-sra -mabi=aapcs-linux -mno-thumb-interwork -mfpu=vfp -funwind-tables -marm -D__LINUX_ARM_ARCH__=6 -march=armv6k -mtune=arm1136j-s -msoft-float -Uarm -fno-delete-null-pointer-checks -O2 --param=allow-store-data-races=0 -Wframe-larger-than=1024 -fno-stack-protector -Wno-unused-but-set-variable -fomit-frame-pointer -fno-var-tracking-assignments -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fconserve-stack -Werror=implicit-int -Werror=strict-prototypes -Werror=date-time -DCC_HAVE_ASM_GOTO -O1 -Wno-error=date-time -Wno-date-time -Wno-unused-variable -Wno-unused-value -Wno-unused-label -Wno-unused-parameter -Wno-unused-function -Wno-unused -Idrivers/net/wireless/realtek/rtl8188EUS/include -Idrivers/net/wireless/realtek/rtl8188EUS/platform -DCONFIG_RTL8188E -DCONFIG_MP_INCLUDED -DCONFIG_TRAFFIC_PROTECT -DCONFIG_LOAD_PHY_PARA_FROM_FILE -DCONFIG_RTW_ADAPTIVITY_EN=0 -DCONFIG_RTW_ADAPTIVITY_MODE=0 -DCONFIG_LITTLE_ENDIAN  -DMODULE  -D"KBUILD_STR(s)=\#s" -D"KBUILD_BASENAME=KBUILD_STR(platform_ops)"  -D"KBUILD_MODNAME=KBUILD_STR(8188eu)" -c -o drivers/net/wireless/realtek/rtl8188EUS/platform/.tmp_platform_ops.o drivers/net/wireless/realtek/rtl8188EUS/platform/platform_ops.c

source_drivers/net/wireless/realtek/rtl8188EUS/platform/platform_ops.o := drivers/net/wireless/realtek/rtl8188EUS/platform/platform_ops.c

deps_drivers/net/wireless/realtek/rtl8188EUS/platform/platform_ops.o := \
    $(wildcard include/config/platform/ops.h) \

drivers/net/wireless/realtek/rtl8188EUS/platform/platform_ops.o: $(deps_drivers/net/wireless/realtek/rtl8188EUS/platform/platform_ops.o)

$(deps_drivers/net/wireless/realtek/rtl8188EUS/platform/platform_ops.o):
